// GENERATED by video/tools/build-beats.py — do not hand-edit.
// Every shot is placed under its own line, force-aligned against
// public/jinn-vo.mp3 by tools/align-vo.py. Order is the recording's,
// not the pack's. Re-run both tools if the VO is recut.

export type Camera = { zoom: number; dx: number; dy: number };

export type Shot = {
  id: string;
  beat: string;
  frameIn: number;
  frames: number;
  tIn: number;
  tOut: number;
  camera: Camera;
  move: string;
  vo: string[];
  lead: number;
  silence: boolean;
  bloom: boolean;
  lineReveal: boolean;
  peak: boolean;
  locked: boolean;
  /** [start, end] of this shot's spoken line, seconds into the VO. */
  line: [number, number];
  plate: string;
};

export const FPS = 30;
export const VO_DURATION = 613.91;
export const DURATION_IN_FRAMES = 18417;
export const WIDTH = 2560;
export const HEIGHT = 1440;

export const SHOTS: Shot[] = [
  {
    "id": "S01",
    "beat": "01 OPEN / THE STAKE",
    "frameIn": 0,
    "frames": 105,
    "tIn": 0.0,
    "tOut": 3.5,
    "camera": {
      "zoom": 0.06,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 6%, centred where the hands meet.",
    "vo": [
      "[serious] Somebody watching this has paid money to have a jinn removed."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      0.0,
      2.94
    ],
    "plate": "plates/S01.png"
  },
  {
    "id": "S01b",
    "beat": "01 OPEN / THE STAKE",
    "frameIn": 105,
    "frames": 162,
    "tIn": 3.5,
    "tOut": 8.896,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold still.",
    "vo": [
      "Maybe not you. Someone you know. A cousin. A friend's mother."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      4.34,
      8.68
    ],
    "plate": "plates/S01b.png"
  },
  {
    "id": "S02",
    "beat": "01 OPEN / THE STAKE",
    "frameIn": 267,
    "frames": 138,
    "tIn": 8.896,
    "tOut": 13.508,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold dead still. Line-reveal permitted.   ** GENERATE FIRST \u2014 reference plate **",
    "vo": [
      "A healer with a phone number, who said he could see what you couldn't."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": true,
    "peak": false,
    "locked": true,
    "line": [
      9.22,
      13.42
    ],
    "plate": "plates/S02.png"
  },
  {
    "id": "S02b",
    "beat": "01 OPEN / THE STAKE",
    "frameIn": 405,
    "frames": 296,
    "tIn": 13.508,
    "tOut": 23.372,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 20.0
    },
    "move": "drift down 20px.",
    "vo": [
      "Then named a price.",
      "I want to show you four verses. By the end you'll know exactly why that man couldn't have done what he promised."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      13.64,
      23.06
    ],
    "plate": "plates/S02b.png"
  },
  {
    "id": "S03",
    "beat": "01 OPEN / THE STAKE",
    "frameIn": 701,
    "frames": 260,
    "tIn": 23.372,
    "tOut": 32.04,
    "camera": {
      "zoom": -0.08,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "pull back 8%, the wash opening out around the shaft.",
    "vo": [
      "The Quran shuts that door completely. Not with a warning \u2014 with a story so humiliating it's hard to hear."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      23.84,
      31.84
    ],
    "plate": "plates/S03.png"
  },
  {
    "id": "S03b",
    "beat": "01 OPEN / THE STAKE",
    "frameIn": 961,
    "frames": 227,
    "tIn": 32.04,
    "tOut": 39.612,
    "camera": {
      "zoom": 0.05,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 5%, very slow.",
    "vo": [
      "But we start somewhere else. With a word you've said a thousand times and never once looked at.",
      "Jinn."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      32.34,
      38.98
    ],
    "plate": "plates/S03b.png"
  },
  {
    "id": "S04",
    "beat": "02 THE ROOT",
    "frameIn": 1188,
    "frames": 460,
    "tIn": 39.612,
    "tOut": 54.928,
    "camera": {
      "zoom": 0.05,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 5%, very slow.",
    "vo": [
      "It isn't a name. It's a description.",
      "The root is three letters. Jeem, noon, noon. They mean: to conceal. To cover something so it can't be seen."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      40.56,
      52.32
    ],
    "plate": "plates/S04.png"
  },
  {
    "id": "S05",
    "beat": "02 THE ROOT",
    "frameIn": 1648,
    "frames": 312,
    "tIn": 54.928,
    "tOut": 65.324,
    "camera": {
      "zoom": 0.0,
      "dx": 40.0,
      "dy": 0.0
    },
    "move": "drift right 40px, revealing more depth in the foliage.",
    "vo": [
      "Janna. Paradise, the garden. Growth so thick the ground disappears under it."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      58.84,
      64.78
    ],
    "plate": "plates/S05.png"
  },
  {
    "id": "S05b",
    "beat": "02 THE ROOT",
    "frameIn": 1960,
    "frames": 174,
    "tIn": 65.324,
    "tOut": 71.12,
    "camera": {
      "zoom": 0.07,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 7%, slow.",
    "vo": [
      "Janeen. An unborn child. Hidden in the womb where nobody can look."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      66.14,
      70.48
    ],
    "plate": "plates/S05b.png"
  },
  {
    "id": "S05c",
    "beat": "02 THE ROOT",
    "frameIn": 2134,
    "frames": 181,
    "tIn": 71.12,
    "tOut": 77.152,
    "camera": {
      "zoom": 0.06,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 6%.",
    "vo": [
      "Majnoon. We translate it madman. It means a mind covered over."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      72.08,
      76.84
    ],
    "plate": "plates/S05c.png"
  },
  {
    "id": "S06",
    "beat": "02 THE ROOT",
    "frameIn": 2315,
    "frames": 175,
    "tIn": 77.152,
    "tOut": 83.012,
    "camera": {
      "zoom": 0.06,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 6%, settling on the boss of the shield.",
    "vo": [
      "And junna. A shield. The thing you get behind so you can't be reached."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      77.62,
      82.78
    ],
    "plate": "plates/S06.png"
  },
  {
    "id": "S06b",
    "beat": "02 THE ROOT",
    "frameIn": 2490,
    "frames": 710,
    "tIn": 83.012,
    "tOut": 106.66,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold dead still \u2014 WASH BLOOM, and the cognate text reveals over it one at a time.",
    "vo": [
      "Same three letters, every time.",
      "That's the whole category. Not evil. Concealed.",
      "And that's where it goes wrong at the start \u2014 because you were handed a category and told it was a character."
    ],
    "lead": 1,
    "silence": false,
    "bloom": true,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      83.36,
      106.26
    ],
    "plate": "plates/S06b.png"
  },
  {
    "id": "S08",
    "beat": "04 IBLIS",
    "frameIn": 3200,
    "frames": 329,
    "tIn": 106.66,
    "tOut": 117.628,
    "camera": {
      "zoom": 0.05,
      "dx": 0.0,
      "dy": 20.0
    },
    "move": "push in 5% and drift down 20px.",
    "vo": [
      "Which brings us to the one everybody gets wrong.",
      "You know the scene. Allah tells the angels to bow to Adam. They bow. One doesn't."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      107.26,
      117.5
    ],
    "plate": "plates/S08.png"
  },
  {
    "id": "S08b",
    "beat": "04 IBLIS",
    "frameIn": 3529,
    "frames": 181,
    "tIn": 117.628,
    "tOut": 123.652,
    "camera": {
      "zoom": 0.0,
      "dx": 30.0,
      "dy": 0.0
    },
    "move": "drift right 30px.",
    "vo": [
      "And every version you've ever been told calls him a fallen angel."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      117.82,
      122.3
    ],
    "plate": "plates/S08b.png"
  },
  {
    "id": "S09",
    "beat": "04 IBLIS",
    "frameIn": 3710,
    "frames": 417,
    "tIn": 123.652,
    "tOut": 137.58,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "none. Absolutely locked off.   ** SILENCE 1 of 3 \u2014 the image holds alone **",
    "vo": [
      "Al-Kahf. Verse fifty. Same scene. Same refusal. Then three words.",
      "Kana min al-jinn.",
      "He was of the jinn. Not an angel. He never was one."
    ],
    "lead": 1,
    "silence": true,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      125.68,
      137.58
    ],
    "plate": "plates/S09.png"
  },
  {
    "id": "S10",
    "beat": "04 IBLIS",
    "frameIn": 4127,
    "frames": 149,
    "tIn": 137.58,
    "tOut": 142.528,
    "camera": {
      "zoom": -0.06,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "pull back 6%, isolating the upright stone.",
    "vo": [
      "And I'll be honest \u2014 I believed the fallen angel version most of my life."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      137.58,
      142.32
    ],
    "plate": "plates/S10.png"
  },
  {
    "id": "S10b",
    "beat": "04 IBLIS",
    "frameIn": 4276,
    "frames": 515,
    "tIn": 142.528,
    "tOut": 159.708,
    "camera": {
      "zoom": 0.05,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 5%.",
    "vo": [
      "Nobody corrected me. It's in the paintings. It's in the way people talk in the masjid car park.",
      "It isn't a small thing to have wrong. It's the entire point of the story."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      142.84,
      153.74
    ],
    "plate": "plates/S10b.png"
  },
  {
    "id": "S11",
    "beat": "04 IBLIS",
    "frameIn": 4791,
    "frames": 608,
    "tIn": 159.708,
    "tOut": 179.96,
    "camera": {
      "zoom": 0.07,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 7%, decisive.",
    "vo": [
      "But he wasn't. He was jinn. Which means he had the one thing angels don't.",
      "A choice. The same thing sitting in your chest right now."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      168.66,
      179.72
    ],
    "plate": "plates/S11.png"
  },
  {
    "id": "S11b",
    "beat": "04 IBLIS",
    "frameIn": 5399,
    "frames": 408,
    "tIn": 179.96,
    "tOut": 193.568,
    "camera": {
      "zoom": -0.06,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "pull back 6%.",
    "vo": [
      "He wasn't a perfect thing that broke. He was a thing that decided.",
      "That's why the story is pointed at you. It only works as a warning if he could have done otherwise. That's one."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      180.32,
      193.24
    ],
    "plate": "plates/S11b.png"
  },
  {
    "id": "S12",
    "beat": "05 NOT ALL EVIL",
    "frameIn": 5807,
    "frames": 765,
    "tIn": 193.568,
    "tOut": 219.064,
    "camera": {
      "zoom": 0.0,
      "dx": -30.0,
      "dy": 0.0
    },
    "move": "drift left 30px, slow. Line-reveal permitted.",
    "vo": [
      "[serious] Second thing. They're not all evil.",
      "Al-Jinn, verse eleven. And notice who's speaking. This is the jinn, talking about themselves.",
      "Among us are the righteous. And among us are others below that."
    ],
    "lead": 2,
    "silence": false,
    "bloom": false,
    "lineReveal": true,
    "peak": false,
    "locked": false,
    "line": [
      194.06,
      218.88
    ],
    "plate": "plates/S12.png"
  },
  {
    "id": "S12b",
    "beat": "05 NOT ALL EVIL",
    "frameIn": 6572,
    "frames": 56,
    "tIn": 219.064,
    "tOut": 220.928,
    "camera": {
      "zoom": 0.06,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 6%.",
    "vo": [
      "We follow different paths."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      219.34,
      220.64
    ],
    "plate": "plates/S12b.png"
  },
  {
    "id": "S13",
    "beat": "05 NOT ALL EVIL",
    "frameIn": 6628,
    "frames": 212,
    "tIn": 220.928,
    "tOut": 227.988,
    "camera": {
      "zoom": 0.06,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 6% on the lit half of the line.",
    "vo": [
      "They have believers. They have disbelievers. The ones who get it right and the ones who don't."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      221.36,
      227.82
    ],
    "plate": "plates/S13.png"
  },
  {
    "id": "S13b",
    "beat": "05 NOT ALL EVIL",
    "frameIn": 6840,
    "frames": 95,
    "tIn": 227.988,
    "tOut": 231.172,
    "camera": {
      "zoom": 0.0,
      "dx": -40.0,
      "dy": 0.0
    },
    "move": "drift left 40px along the doors.",
    "vo": [
      "Exactly like the street you live on."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      228.24,
      230.98
    ],
    "plate": "plates/S13b.png"
  },
  {
    "id": "S13c",
    "beat": "05 NOT ALL EVIL",
    "frameIn": 6935,
    "frames": 556,
    "tIn": 231.172,
    "tOut": 249.688,
    "camera": {
      "zoom": 0.05,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 5%, settling. WASH BLOOM as the lamps take light.",
    "vo": [
      "Two verses later: when we heard the guidance, we believed in it.",
      "So jinn was never another word for shaytan. Hold onto that. It comes back at the end. That's two."
    ],
    "lead": 0,
    "silence": false,
    "bloom": true,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      231.46,
      247.92
    ],
    "plate": "plates/S13c.png"
  },
  {
    "id": "S16b",
    "beat": "07 PURPOSE",
    "frameIn": 7491,
    "frames": 248,
    "tIn": 249.688,
    "tOut": 257.98,
    "camera": {
      "zoom": 0.05,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 5%.",
    "vo": [
      "You've spent your whole life reading a book that was never addressed to you alone."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      252.34,
      257.62
    ],
    "plate": "plates/S16b.png"
  },
  {
    "id": "S17",
    "beat": "08 WHAT THEY CAN DO",
    "frameIn": 7739,
    "frames": 489,
    "tIn": 257.98,
    "tOut": 274.276,
    "camera": {
      "zoom": -0.08,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "pull back 8%, revealing the scale of the hall.",
    "vo": [
      "[serious] So what can they actually do?",
      "Sulayman, peace be upon him, had them under his command. Not summoned. Given, by Allah.",
      "An-Naml describes his court. His soldiers of the jinn, and men, and birds."
    ],
    "lead": 2,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      258.52,
      273.94
    ],
    "plate": "plates/S17.png"
  },
  {
    "id": "S17b",
    "beat": "08 WHAT THEY CAN DO",
    "frameIn": 8228,
    "frames": 232,
    "tIn": 274.276,
    "tOut": 282.008,
    "camera": {
      "zoom": 0.06,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 6% up the steps.",
    "vo": [
      "He needed a throne brought from another kingdom. An ifrit said he'd have it there before Sulayman could stand up."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      274.78,
      281.44
    ],
    "plate": "plates/S17b.png"
  },
  {
    "id": "S18",
    "beat": "08 WHAT THEY CAN DO",
    "frameIn": 8460,
    "frames": 201,
    "tIn": 282.008,
    "tOut": 288.716,
    "camera": {
      "zoom": 0.07,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 7% on the vessel.",
    "vo": [
      "Surah Sad describes the rest in four words. Every builder and diver."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      282.86,
      287.98
    ],
    "plate": "plates/S18.png"
  },
  {
    "id": "S18b",
    "beat": "08 WHAT THEY CAN DO",
    "frameIn": 8661,
    "frames": 416,
    "tIn": 288.716,
    "tOut": 302.56,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": -30.0
    },
    "move": "drift up 30px through the levels.",
    "vo": [
      "Saba lists what they made. Elevated chambers. Basins the size of reservoirs. Cauldrons too heavy to move.",
      "So this isn't nothing. Strength. Speed. Real, physical power."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      289.82,
      300.92
    ],
    "plate": "plates/S18b.png"
  },
  {
    "id": "S19",
    "beat": "08 WHAT THEY CAN DO",
    "frameIn": 9077,
    "frames": 499,
    "tIn": 302.56,
    "tOut": 319.204,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold dead still.",
    "vo": [
      "But look at the conditions. Under a prophet. By Allah's permission. Once, in all of recorded history.",
      "Never for sale. Never for you."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      305.02,
      317.62
    ],
    "plate": "plates/S19.png"
  },
  {
    "id": "S20",
    "beat": "09 THE DEATH",
    "frameIn": 9576,
    "frames": 167,
    "tIn": 319.204,
    "tOut": 324.772,
    "camera": {
      "zoom": 0.04,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 4%, barely perceptible. Line-reveal permitted.",
    "vo": [
      "And then Sulayman died.",
      "He died standing up. Leaning on his staff."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": true,
    "peak": false,
    "locked": false,
    "line": [
      321.58,
      324.46
    ],
    "plate": "plates/S20.png"
  },
  {
    "id": "S20b",
    "beat": "09 THE DEATH",
    "frameIn": 9743,
    "frames": 68,
    "tIn": 324.772,
    "tOut": 327.02,
    "camera": {
      "zoom": -0.1,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "pull back 10%, the room opening around the staff.",
    "vo": [
      "And nobody noticed."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      325.24,
      326.46
    ],
    "plate": "plates/S20b.png"
  },
  {
    "id": "S21",
    "beat": "09 THE DEATH",
    "frameIn": 9811,
    "frames": 148,
    "tIn": 327.02,
    "tOut": 331.956,
    "camera": {
      "zoom": 0.0,
      "dx": 40.0,
      "dy": 0.0
    },
    "move": "drift right 40px across the work.",
    "vo": [
      "The jinn kept working. Cutting. Lifting. Carrying."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      327.86,
      331.66
    ],
    "plate": "plates/S21.png"
  },
  {
    "id": "S21b",
    "beat": "09 THE DEATH",
    "frameIn": 9959,
    "frames": 382,
    "tIn": 331.956,
    "tOut": 344.696,
    "camera": {
      "zoom": 0.08,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 8%.",
    "vo": [
      "Building the thing he'd told them to build. For a man who was already dead.",
      "The Quran doesn't say how long. Days. Weeks. Long enough that it mattered."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      332.4,
      344.36
    ],
    "plate": "plates/S21b.png"
  },
  {
    "id": "S22",
    "beat": "09 THE DEATH",
    "frameIn": 10341,
    "frames": 173,
    "tIn": 344.696,
    "tOut": 350.48,
    "camera": {
      "zoom": 0.1,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 10%. The most decisive move in the film.   ** PEAK **",
    "vo": [
      "Until a small creature of the earth ate through the wood of that staff."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": true,
    "locked": false,
    "line": [
      345.2,
      350.12
    ],
    "plate": "plates/S22.png"
  },
  {
    "id": "S22b",
    "beat": "09 THE DEATH",
    "frameIn": 10514,
    "frames": 387,
    "tIn": 350.48,
    "tOut": 363.364,
    "camera": {
      "zoom": 0.09,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 9%, following the line down.",
    "vo": [
      "And he fell. Saba, verse fourteen.",
      "When he fell, it became clear to the jinn \u2014 that if they had known the unseen, they would never have stayed in that humiliating labour."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      351.02,
      362.74
    ],
    "plate": "plates/S22b.png"
  },
  {
    "id": "S23",
    "beat": "09 THE DEATH",
    "frameIn": 10901,
    "frames": 392,
    "tIn": 363.364,
    "tOut": 376.42,
    "camera": {
      "zoom": 0.04,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold dead still four seconds, then push in 4%.   ** SILENCE 2 of 3 \u2014 the image holds alone **",
    "vo": [
      "They could not see a dead man standing in front of them.",
      "Of every example Allah could have chosen, He chose that one. Not a rule. Not a lecture."
    ],
    "lead": 0,
    "silence": true,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      364.3,
      376.14
    ],
    "plate": "plates/S23.png"
  },
  {
    "id": "S23b",
    "beat": "09 THE DEATH",
    "frameIn": 11293,
    "frames": 240,
    "tIn": 376.42,
    "tOut": 384.448,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold dead still.",
    "vo": [
      "A room full of them, working for a corpse, because they couldn't see what was standing six feet away."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      376.84,
      384.12
    ],
    "plate": "plates/S23b.png"
  },
  {
    "id": "S24",
    "beat": "10 THE FRAUD + CTA",
    "frameIn": 11533,
    "frames": 675,
    "tIn": 384.448,
    "tOut": 406.928,
    "camera": {
      "zoom": 0.08,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 8% onto the notes.",
    "vo": [
      "That's three. And it's the one that costs people money.",
      "Because if they can't see a dead king in the room \u2014 they cannot see your future.",
      "So the man who told you he'd consulted one, then named his price..."
    ],
    "lead": 2,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      384.94,
      406.72
    ],
    "plate": "plates/S24.png"
  },
  {
    "id": "S24b",
    "beat": "10 THE FRAUD + CTA",
    "frameIn": 12208,
    "frames": 123,
    "tIn": 406.928,
    "tOut": 411.036,
    "camera": {
      "zoom": 0.1,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 10%. Hard \u2014 the hardest move in the film after S22.",
    "vo": [
      "...was selling you something the Quran took apart fourteen hundred years ago."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      407.24,
      409.7
    ],
    "plate": "plates/S24b.png"
  },
  {
    "id": "S24c",
    "beat": "10 THE FRAUD + CTA",
    "frameIn": 12331,
    "frames": 362,
    "tIn": 411.036,
    "tOut": 423.112,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold still.",
    "vo": [
      "[warmly] If that's useful to someone you know, send it to them. And subscribe, because there's one more \u2014 and it's the one that changes what you do tonight."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      413.04,
      422.72
    ],
    "plate": "plates/S24c.png"
  },
  {
    "id": "S25",
    "beat": "11 THE TRAVELLER",
    "frameIn": 12693,
    "frames": 291,
    "tIn": 423.112,
    "tOut": 432.8,
    "camera": {
      "zoom": -0.1,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "pull back 10%, the valley opening around the objects.",
    "vo": [
      "Number four. Picture it, because people really did this.",
      "You're travelling. Night comes down in a valley you don't know."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      423.7,
      432.6
    ],
    "plate": "plates/S25.png"
  },
  {
    "id": "S25b",
    "beat": "11 THE TRAVELLER",
    "frameIn": 12984,
    "frames": 72,
    "tIn": 432.8,
    "tOut": 435.184,
    "camera": {
      "zoom": -0.1,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "pull back 10%.",
    "vo": [
      "You're sleeping out in the open."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      433.1,
      434.84
    ],
    "plate": "plates/S25b.png"
  },
  {
    "id": "S25c",
    "beat": "11 THE TRAVELLER",
    "frameIn": 13056,
    "frames": 469,
    "tIn": 435.184,
    "tOut": 450.84,
    "camera": {
      "zoom": 0.06,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 6%.",
    "vo": [
      "And before you lie down you say it out loud: I seek refuge with the master of this place. Keep me safe tonight.",
      "That was ordinary. That was normal practice."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      435.7,
      448.68
    ],
    "plate": "plates/S25c.png"
  },
  {
    "id": "S26",
    "beat": "11 THE TRAVELLER",
    "frameIn": 13525,
    "frames": 844,
    "tIn": 450.84,
    "tOut": 478.98,
    "camera": {
      "zoom": -0.12,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "pull back 12%, the weight becoming visible as the frame widens.",
    "vo": [
      "Al-Jinn, verse six. And there were men from mankind who sought refuge in men from the jinn \u2014 so they only increased them in burden.",
      "One word carries the verdict. Rahaqa.",
      "They asked for protection. What they got was weight."
    ],
    "lead": 2,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      454.08,
      477.3
    ],
    "plate": "plates/S26.png"
  },
  {
    "id": "S26b",
    "beat": "11 THE TRAVELLER",
    "frameIn": 14369,
    "frames": 331,
    "tIn": 478.98,
    "tOut": 489.992,
    "camera": {
      "zoom": 0.0,
      "dx": 40.0,
      "dy": 0.0
    },
    "move": "drift right 40px, following.",
    "vo": [
      "Seeking safety from something hidden doesn't make you safe. It makes you owned.",
      "That's four."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      481.5,
      489.52
    ],
    "plate": "plates/S26b.png"
  },
  {
    "id": "S27",
    "beat": "12 THE WHISPERER",
    "frameIn": 14700,
    "frames": 352,
    "tIn": 489.992,
    "tOut": 501.724,
    "camera": {
      "zoom": 0.0,
      "dx": 40.0,
      "dy": 0.0
    },
    "move": "drift right 40px, past the openings.",
    "vo": [
      "[serious] Which brings us back to the word I told you to hold. Shaytan.",
      "Al-An'am, verse one hundred and twelve. Shayateen of mankind and jinn."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      490.7,
      501.26
    ],
    "plate": "plates/S27.png"
  },
  {
    "id": "S27b",
    "beat": "12 THE WHISPERER",
    "frameIn": 15052,
    "frames": 153,
    "tIn": 501.724,
    "tOut": 506.832,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold dead still.",
    "vo": [
      "Devils from among the jinn. And devils from among people."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      502.42,
      506.52
    ],
    "plate": "plates/S27b.png"
  },
  {
    "id": "S28",
    "beat": "12 THE WHISPERER",
    "frameIn": 15205,
    "frames": 1299,
    "tIn": 506.832,
    "tOut": 550.124,
    "camera": {
      "zoom": 0.09,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 9%, ending on the empty chair opposite. Line-reveal permitted. ** THE THESIS SHOT \u00b7 SILENCE 3 of 3 **",
    "vo": [
      "Then the very last surah in the Quran. An-Nas. Min al-jinnati wan-nas.",
      "Some of it has a face. And a name. And a phone number.",
      "Some of it is sitting across the table from you, asking for cash."
    ],
    "lead": 2,
    "silence": true,
    "bloom": false,
    "lineReveal": true,
    "peak": false,
    "locked": false,
    "line": [
      507.3,
      549.7
    ],
    "plate": "plates/S28.png"
  },
  {
    "id": "S28b",
    "beat": "12 THE WHISPERER",
    "frameIn": 16504,
    "frames": 118,
    "tIn": 550.124,
    "tOut": 554.072,
    "camera": {
      "zoom": 0.09,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 9%, ending on the empty chair.",
    "vo": [
      "You've spent your life afraid of the hidden one."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      550.76,
      553.8
    ],
    "plate": "plates/S28b.png"
  },
  {
    "id": "S28c",
    "beat": "12 THE WHISPERER",
    "frameIn": 16622,
    "frames": 130,
    "tIn": 554.072,
    "tOut": 558.416,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold dead still.",
    "vo": [
      "The Book closes by pointing at the visible one."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      554.48,
      558.12
    ],
    "plate": "plates/S28c.png"
  },
  {
    "id": "S29b",
    "beat": "13 THE CLOSE",
    "frameIn": 16752,
    "frames": 474,
    "tIn": 558.416,
    "tOut": 574.204,
    "camera": {
      "zoom": 0.0,
      "dx": 30.0,
      "dy": 0.0
    },
    "move": "drift right 30px along the row. WASH BLOOM as the lamp is uncovered.",
    "vo": [
      "[calm] So bring it back to those three letters. Jinn. The concealed. Janeen. Janna. Majnoon. And junna. The shield."
    ],
    "lead": 0,
    "silence": false,
    "bloom": true,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      558.86,
      573.82
    ],
    "plate": "plates/S29b.png"
  },
  {
    "id": "S29",
    "beat": "13 THE CLOSE",
    "frameIn": 17226,
    "frames": 400,
    "tIn": 574.204,
    "tOut": 587.532,
    "camera": {
      "zoom": 0.05,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 5%, settling.",
    "vo": [
      "Notice what the Quran never does. It never hands you a technique for the unseen. No formula. Nobody to pay.",
      "It hands you a junna."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      574.78,
      587.18
    ],
    "plate": "plates/S29.png"
  },
  {
    "id": "S29c",
    "beat": "13 THE CLOSE",
    "frameIn": 17626,
    "frames": 226,
    "tIn": 587.532,
    "tOut": 595.072,
    "camera": {
      "zoom": 0.05,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "push in 5%.",
    "vo": [
      "Al-Fatiha. Ayat al-Kursi. The last two surahs. The words in the morning and the words at night."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      588.06,
      594.88
    ],
    "plate": "plates/S29c.png"
  },
  {
    "id": "S30",
    "beat": "13 THE CLOSE",
    "frameIn": 17852,
    "frames": 282,
    "tIn": 595.072,
    "tOut": 604.47,
    "camera": {
      "zoom": -0.12,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "pull back 12% \u2014 the widest move in the film, saved for last.   ** CLOSING FRAME **",
    "vo": [
      "Protection that never once asks you to negotiate with anything hidden \u2014 because it comes from the One who made the hidden thing in the first place.",
      "[warmly] Only One sees both."
    ],
    "lead": 1,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": false,
    "line": [
      595.36,
      604.45
    ],
    "plate": "plates/S30.png"
  },
  {
    "id": "S30b",
    "beat": "13 THE CLOSE",
    "frameIn": 18134,
    "frames": 283,
    "tIn": 604.47,
    "tOut": 613.91,
    "camera": {
      "zoom": 0.0,
      "dx": 0.0,
      "dy": 0.0
    },
    "move": "hold dead still, then cut to S30.",
    "vo": [
      "They were made from fire. You were made from clay.",
      "Neither of you was ever built to see the other."
    ],
    "lead": 0,
    "silence": false,
    "bloom": false,
    "lineReveal": false,
    "peak": false,
    "locked": true,
    "line": [
      604.5,
      611.06
    ],
    "plate": "plates/S30b.png"
  }
];

// Shots the recording does not contain — the pack's CUT 1 and CUT 2,
// applied when the VO was recorded. Their plates are still in
// public/plates/ and they return automatically if a fuller VO lands.
export const DROPPED: string[] = ["S07", "S07b", "S07c", "S14", "S14b", "S15", "S15b", "S16"];
