#!/usr/bin/env python3
"""Write src/jinn/plates.ts from whatever is actually in public/plates/.

The film renders with procedural stand-ins for every plate that has not landed
yet, so the cut can be judged before the illustrations exist. Drop a real
<shot-id>.png in public/plates/ and re-run this; nothing else changes.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
plates = sorted(
    p.stem for p in (ROOT / "public" / "plates").glob("*") if p.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp"}
)
(ROOT / "src" / "jinn" / "plates.ts").write_text(
    "// GENERATED by video/tools/scan-plates.py — do not hand-edit.\n"
    "// Shot ids with a real illustration in public/plates/.\n\n"
    f"export const PLATES: string[] = {plates!r};\n".replace("'", '"'),
    encoding="utf-8",
)
print(f"{len(plates)} plate(s) present")
