#!/usr/bin/env python3
"""Write src/jinn/plates.ts from whatever is actually in public/plates/.

Also measures each plate's tone. The delivered art runs from bare parchment to
a full indigo night wash, and cream type is illegible on the first while ink
type is illegible on the second. Rather than hand-tag 64 shots, this reads the
mean luminance of the band the caption actually occupies (the lower third) and
lets the type layer pick ink-on-paper or cream-on-night per shot.

Drop a real <shot-id>.png in public/plates/ and re-run. Shots without a plate
render the procedural stand-in.
"""
from pathlib import Path

from PIL import Image, ImageStat

ROOT = Path(__file__).resolve().parents[1]
PLATE_DIR = ROOT / "public" / "plates"

plates, tone = [], {}
for p in sorted(PLATE_DIR.glob("*")):
    if p.suffix.lower() not in {".png", ".jpg", ".jpeg", ".webp"}:
        continue
    plates.append(p.stem)
    im = Image.open(p).convert("L")
    band = im.crop((0, int(im.height * 0.62), im.width, im.height))
    tone[p.stem] = round(ImageStat.Stat(band).mean[0] / 255, 3)

body = ",\n".join(f'  "{k}": {v}' for k, v in sorted(tone.items()))
(ROOT / "src" / "jinn" / "plates.ts").write_text(
    "// GENERATED by video/tools/scan-plates.py — do not hand-edit.\n"
    "// Shot ids with a real illustration in public/plates/, and the mean\n"
    "// luminance (0-1) of the band the caption sits in, used to decide\n"
    "// ink-on-paper versus cream-on-night type per shot.\n\n"
    "export const PLATES: string[] = [\n"
    + "".join(f'  "{s}",\n' for s in plates)
    + "];\n\n"
    "export const PLATE_TONE: Record<string, number> = {\n"
    + body
    + ",\n};\n\n"
    "/** True when the caption band is light enough to want ink type.\n"
    " *  An unmeasured id is on the procedural stand-in, which is parchment. */\n"
    "export const isLight = (id: string): boolean => (PLATE_TONE[id] ?? 1) > 0.52;\n",
    encoding="utf-8",
)
light = sum(1 for v in tone.values() if v > 0.52)
print(f"{len(plates)} plate(s): {light} light, {len(plates)-light} dark")
