#!/usr/bin/env python3
"""Render each caption cue to a transparent 1080x1920 PNG.

Arabic is shaped by PIL's raqm/HarfBuzz layout engine (direction='rtl'),
so the Qur'anic text keeps its harakat and joins correctly. Nothing here
is generated by an image model.
"""
import os
from PIL import Image, ImageDraw, ImageFont, ImageFilter
from beats import CUES, W, H

F = "fonts"
FONT_EN = f"{F}/montserrat-latin-800-normal.ttf"
FONT_AR = f"{F}/AmiriQuran.ttf"

GOLD   = (232, 200, 119, 255)
CREAM  = (247, 235, 214, 255)
WHITE  = (255, 255, 255, 255)
DIMGLD = (201, 169, 97, 255)

# kind -> (font, size, colour, line-gap, y centre)
STYLE = {
    "hook":      (FONT_EN, 118, WHITE,  24, 1320),
    "en":        (FONT_EN,  84, WHITE,  20, 1335),
    "scripture": (FONT_EN,  80, CREAM,  20, 1335),
    "ref":       (FONT_EN,  46, DIMGLD, 14, 1370),
    "ar":        (FONT_AR, 190, GOLD,  130,  880),
    "ar_small":  (FONT_AR, 170, GOLD,   90, 1300),
}

MAXW = 980          # keep every line inside the safe width


def kwargs(font, rtl):
    k = {"font": font, "anchor": "mm"}
    if rtl:
        k.update(direction="rtl", language="ar")
    return k


# Montserrat has no U+FDFA (ﷺ); fall back to Amiri for any glyph it lacks.
_cmap = None


def _covered(ch):
    global _cmap
    if _cmap is None:
        from fontTools.ttLib import TTFont
        _cmap = set(TTFont(FONT_EN).getBestCmap().keys())
    return ord(ch) in _cmap


def runs(text, size):
    """Split a Latin line into (segment, font) runs, swapping in Amiri
    for glyphs Montserrat cannot render."""
    out, cur, cur_ok = [], "", None
    for ch in text:
        ok = _covered(ch)
        if cur_ok is None or ok == cur_ok:
            cur, cur_ok = cur + ch, ok
        else:
            out.append((cur, cur_ok))
            cur, cur_ok = ch, ok
    if cur:
        out.append((cur, cur_ok))
    return [(s, ImageFont.truetype(FONT_EN if ok else FONT_AR,
                                   size if ok else int(size * 1.25)))
            for s, ok in out]


def draw_mixed(d, xy, text, size, fill):
    """Centre-draw a line that may mix Montserrat and Amiri glyphs."""
    segs = runs(text, size)
    widths = [d.textlength(s, font=f) for s, f in segs]
    x = xy[0] - sum(widths) / 2
    for (s, f), w in zip(segs, widths):
        d.text((x, xy[1]), s, font=f, fill=fill, anchor="lm")
        x += w


def render(idx, kind, text):
    font_path, size, colour, gap, cy = STYLE[kind]
    rtl = kind.startswith("ar")

    lines = text.split("\n")
    if kind == "ref":                       # fake letter-spacing
        lines = [" ".join(l) for l in lines]

    # shrink to fit the safe width
    probe = ImageDraw.Draw(Image.new("RGBA", (W, H)))
    while size > 24:
        font = ImageFont.truetype(font_path, size)
        mk = {"font": font}
        if rtl:
            mk.update(direction="rtl", language="ar")
        if max(probe.textlength(l, **mk) for l in lines) <= MAXW:
            break
        size = int(size * 0.94)
    font = ImageFont.truetype(font_path, size)

    lh = size + gap
    y0 = cy - (lh * len(lines)) / 2 + lh / 2

    # blurred black plate behind the type, stacked for density
    def paint(d, fill):
        for i, l in enumerate(lines):
            xy = (W / 2, y0 + i * lh)
            if rtl:
                d.text(xy, l, fill=fill, **kwargs(font, rtl))
            else:
                draw_mixed(d, xy, l, size, fill)

    shadow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    paint(ImageDraw.Draw(shadow), (0, 0, 0, 255))
    shadow = shadow.filter(ImageFilter.GaussianBlur(24))

    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    for _ in range(4):
        layer = Image.alpha_composite(layer, shadow)

    paint(ImageDraw.Draw(layer), colour)

    out = f"work/caps/c{idx:02d}.png"
    layer.save(out)
    return size


os.makedirs("work/caps", exist_ok=True)
for i, (st, en, kind, text) in enumerate(CUES):
    s = render(i, kind, text)
    print(f"{i:02d} {st:6.2f}-{en:6.2f} {kind:10s} px={s}")
print(f"\n{len(CUES)} cues rendered")
